version: '3.8'

services:
  cassandra:
    build:
      context: .
      dockerfile: Dockerfile  # Utilise le Dockerfile pour construire l'image
    container_name: cassandra-container
    environment:
      - CASSANDRA_CLUSTER_NAME=CassandraCluster
      - CASSANDRA_DC=DC1
      - CASSANDRA_RACK=Rack1
    ports:
      - "9042:9042"  # Port pour CQLSH et clients Cassandra